background = #080706
foreground = #ECC18E
cursor-color = #f1d1aa
selection-background = #1a1a1a
selection-foreground = #ECC18E

palette = 0=#080706
palette = 1=#ba8565
palette = 2=#e1b975
palette = 3=#ffe395
palette = 4=#ac6766
palette = 5=#e3907a
palette = 6=#f1d672
palette = 7=#ECC18E
palette = 8=#686163
palette = 9=#d9976e
palette = 10=#ffcd72
palette = 11=#ffe37f
palette = 12=#cb7776
palette = 13=#ff9f82
palette = 14=#ffec6b
palette = 15=#f1d1aa
