foreground #ECC18E
background #080706
selection_foreground #ECC18E
selection_background #1a1a1a

cursor #f1d1aa
cursor_text_color #080706

active_border_color #ac6766
active_tab_background #ac6766

color0 #080706
color1 #ba8565
color2 #e1b975
color3 #ffe395
color4 #ac6766
color5 #e3907a
color6 #f1d672
color7 #ECC18E
color8 #686163
color9 #d9976e
color10 #ffcd72
color11 #ffe37f
color12 #cb7776
color13 #ff9f82
color14 #ffec6b
color15 #f1d1aa
